# Generated by Django 3.0.3 on 2020-05-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0002_auto_20200303_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measure',
            old_name='type',
            new_name='Codigo',
        ),
    ]
