# Generated by Django 3.0.3 on 2020-05-19 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0002_auto_20200303_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='type',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='value',
        ),
        migrations.AddField(
            model_name='measure',
            name='Area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure',
            name='Codigo',
            field=models.CharField(default=0, max_length=20, verbose_name='Codigo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure',
            name='Latitud',
            field=models.CharField(default=0, max_length=3, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure',
            name='Longitud',
            field=models.CharField(default=0, max_length=3, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure',
            name='Producto',
            field=models.CharField(default=0, max_length=20, verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
