# Generated by Django 3.0.3 on 2020-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0003_auto_20200515_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='value',
        ),
        migrations.AddField(
            model_name='measure',
            name='Longitud',
            field=models.CharField(default=0, max_length=3, verbose_name='Longitud'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measure',
            name='Codigo',
            field=models.CharField(max_length=20, verbose_name='Codigo'),
        ),
    ]
