# Generated by Django 3.0.3 on 2020-05-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0004_auto_20200515_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='Latitud',
            field=models.CharField(default=0, max_length=3, verbose_name='Latitud'),
            preserve_default=False,
        ),
    ]
