# Generated by Django 3.0.3 on 2020-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0005_measure_latitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='Producto',
            field=models.CharField(default=0, max_length=20, verbose_name='Latitud'),
            preserve_default=False,
        ),
    ]
