# Generated by Django 3.0.3 on 2020-05-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0007_auto_20200515_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='Area',
            field=models.IntegerField(default=0, verbose_name='Area'),
            preserve_default=False,
        ),
    ]
