# Generated by Django 3.0.3 on 2020-05-15 22:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0008_measure_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='Area',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator('0.01')], verbose_name='Area'),
        ),
    ]
